// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBdVkgPPqCYeXO7lilj9_oOrCTFi9-Y9oQ',
    appId: '1:692796480383:android:998ae118b423a67471d84a',
    messagingSenderId: '692796480383',
    projectId: 'prod-nightowl',
    storageBucket: 'prod-nightowl.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDnGxIn0XuXQQTOorLr9_Cd8EP47rg_760',
    appId: '1:692796480383:ios:5d9577a582d0e27071d84a',
    messagingSenderId: '692796480383',
    projectId: 'prod-nightowl',
    storageBucket: 'prod-nightowl.firebasestorage.app',
    iosBundleId: 'com.nightowl.nightowlcode',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDMGbV5e5AEuDekNyPLqDje29Q4S3Kinm4',
    appId: '1:692796480383:web:59e79b7cf51406d771d84a',
    messagingSenderId: '692796480383',
    projectId: 'prod-nightowl',
    authDomain: 'prod-nightowl.firebaseapp.com',
    storageBucket: 'prod-nightowl.firebasestorage.app',
    measurementId: 'G-MS2Y6RF8YD',
  );
}
